import { FC } from "react";
import Head from "next/head";

type Props = {
  name: string;
};

const Home: FC<Props> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Nothing :D
    </div>
  );
};

export default Home;
